theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Tokugawa Travel
description: A gathering of research about travel and tourism in Tokugawa Japan
url: "https://hall-naiya.github.io/"
markdown: kramdown
image: travel.jpg
