theme: jekyll-theme-slate
title: Tokugawa Travel
description: This a gathering of research about travel and tourism in Tokugawa Japan
plugins:
  - jemoji
url: "https://hall-naiya.github.io/"
markdown: kramdown
  background-image: url("https://www.jstor.org/stable/community.23870769");
  background-size: 100% auto;